[[redirects]]
  from = "/metrics/host-metrics/heroku.html"
  to = "/heroku/host-metrics.html"
[[redirects]]
  from = "/contributing"
  to = "/appsignal/contributing.html"
[[redirects]]
  from = "/getting-started/your-user-account.html"
  to = "/user-account/index.html"
[[redirects]]
  from = "/getting-started/user-account.html"
  to = "/user-account/index.html"
[[redirects]]
  from = "/getting-started/invite-new-members.html"
  to = "/organization/team/members.html"
[[redirects]]
  from = "/getting-started/manage-owners-teams.html"
  to = "/organization/team/owners.html"
[[redirects]]
  from = "/getting-started/set-up-a-new-app.html"
  to = "/guides/new-application.html"
[[redirects]]
  from = "/getting-started/new-application.html"
  to = "/guides/new-application.html"
[[redirects]]
  from = "/application/new-application.html"
  to = "/guides/new-application.html"
[[redirects]]
  from = "/getting-started/manage-app-settings.html"
  to = "/application/settings.html"
[[redirects]]
  from = "/getting-started/lifecycle.html"
  to = "/appsignal/data-life-cycle.html"
[[redirects]]
  from = "/appsignal/request-lifecycle.html"
  to = "/appsignal/data-life-cycle.html"
[[redirects]]
  from = "/getting-started/how-appsignal-operates.html"
  to = "/appsignal/how-appsignal-operates.html"
[[redirects]]
  from = "/getting-started/custom-metrics.html"
  to = "/metrics/custom.html"
[[redirects]]
  from = "/getting-started/host-metrics.html"
  to = "/metrics/host.html"
[[redirects]]
  from = "/getting-started/integrations.html"
  to = "/application/integrations/index.html"
[[redirects]]
  from = "/getting-started/integrations/pagerduty.html"
  to = "/application/integrations/pagerduty.html"
[[redirects]]
  from = "/getting-started/integrations/jira.html"
  to = "/application/integrations/jira.html"
[[redirects]]
  from = "/getting-started/integrations/intercom.html"
  to = "/application/integrations/intercom.html"
[[redirects]]
  from = "/getting-started/webhooks.html"
  to = "/application/integrations/webhooks.html"
[[redirects]]
  from = "/billing/declined-charges.html"
  to = "/organization/billing.html"
[[redirects]]
  from = "/tweaks-in-your-code/filter-parameter-logging.html"
  to = "/ruby/configuration/parameter-filtering.html"
[[redirects]]
  from = "/tweaks-in-your-code/integration-appsignal.html"
  to = "/ruby/instrumentation/integrating-appsignal.html"
[[redirects]]
  from = "/tweaks-in-your-code/handle-exceptions.html"
  to = "/ruby/instrumentation/handle-exceptions.html"
[[redirects]]
  from = "/ruby/instrumentation/handle-exceptions.html"
  to = "/ruby/instrumentation/exception-handling.html"
[[redirects]]
  from = "/tweaks-in-your-code/integration-gems.html"
  to = "/ruby/integrations/appsignal-gems.html"
[[redirects]]
  from = "/tweaks-in-your-code/custom-instrumentation.html"
  to = "/ruby/instrumentation/index.html"
[[redirects]]
  from = "/tweaks-in-your-code/method-instrumentation.html"
  to = "/ruby/instrumentation/method-instrumentation.html"
[[redirects]]
  from = "/tweaks-in-your-code/link-templates.html"
  to = "/ruby/instrumentation/link-templates.html"
[[redirects]]
  from = "/getting-started/supported-frameworks.html"
  to = "/ruby/integrations/index.html"
[[redirects]]
  from = "/gem-settings/configuration.html"
  to = "/ruby/configuration/index.html"
[[redirects]]
  from = "/ruby/configuration.html"
  to = "/ruby/configuration/index.html"
[[redirects]]
  from = "/gem-settings/ignore-actions.html"
  to = "/ruby/configuration/ignore-actions.html"
[[redirects]]
  from = "/tweaks-in-your-code/ignore-instrumentation.html"
  to = "/ruby/instrumentation/ignore-instrumentation.html"
[[redirects]]
  from = "/tweaks-in-your-code/frontend-error-catching.html"
  to = "/front-end/error-handling.html"
[[redirects]]
  from = "/tweaks-in-your-code/background-monitoring.html"
  to = "/ruby/integrations/index.html"
[[redirects]]
  from = "/background-monitoring/sidekiq.html"
  to = "/ruby/integrations/sidekiq.html"
[[redirects]]
  from = "/background-monitoring/delayed-job.html"
  to = "/ruby/integrations/delayed-job.html"
[[redirects]]
  from = "/background-monitoring/resque.html"
  to = "/ruby/integrations/resque.html"
[[redirects]]
  from = "/background-monitoring/rake.html"
  to = "/ruby/integrations/rake.html"
[[redirects]]
  from = "/background-monitoring/custom.html"
  to = "/ruby/instrumentation/background-jobs.html"
[[redirects]]
  from = "/security/overview.html"
  to = "/appsignal/security.html"
[[redirects]]
  from = "/api/overview.html"
  to = "/api/index.html"
[[redirects]]
  from = "/ruby/instrumentation/link-templates.html"
  to = "/application/link-templates.html"
[[redirects]]
  from = "/push-api/overview.html"
  to = "/push-api/markers.html"
[[redirects]]
  from = "/organization/team/index.html"
  to = "/organization/team/members.html"
[[redirects]]
  from = "/ruby/installation.html"
  to = "/ruby/installation/index.html"
[[redirects]]
  from = "/elixir/installation.html"
  to = "/elixir/installation/index.html"
[[redirects]]
  from = "/metrics/custom-metrics/dashboards.html"
  to = "/metrics/dashboards.html"
[[redirects]]
  from = "/metrics/host.html"
  to = "/metrics/host-metrics/index.html"
[[redirects]]
  from = "/appsignal/contributing.html"
  to = "/appsignal/contributing/index.html"
[[redirects]]
  from = "/appsignal/code-of-conduct.html"
  to = "/appsignal/contributing/code-of-conduct.html"
[[redirects]]
  from = "/application/anomaly-detection/index.html"
  to = "/anomaly-detection/index.html"
[[redirects]]
  from = "/application/anomaly-detection/"
  to = "/anomaly-detection/index.html"
[[redirects]]
  from = "/ruby/configuration/parameter-filtering.html"
  to = "/application/parameter-filtering.html"
[[redirects]]
  from = "/elixir/configuration/parameter-filtering.html"
  to = "/application/parameter-filtering.html"
[[redirects]]
  from = "/ruby/configuration/session-data-filtering.html"
  to = "/application/session-data-filtering.html"
[[redirects]]
  from = "/elixir/configuration/session-data-filtering.html"
  to = "/application/session-data-filtering.html"
[[redirects]]
  from = "/ruby/configuration/ignore-errors.html"
  to = "/guides/filter-data/ignore-errors.html"
[[redirects]]
  from = "/elixir/configuration/ignore-errors.html"
  to = "/guides/filter-data/ignore-errors.html"
[[redirects]]
  from = "/nodejs/configuration/ignore-errors.html"
  to = "/guides/filter-data/ignore-errors.html"
[[redirects]]
  from = "/ruby/configuration/ignore-actions.html"
  to = "/guides/filter-data/ignore-actions.html"
[[redirects]]
  from = "/elixir/configuration/ignore-actions.html"
  to = "/guides/filter-data/ignore-actions.html"
[[redirects]]
  from = "/nodejs/configuration/ignore-actions.html"
  to = "/guides/filter-data/ignore-actions.html"
[[redirects]]
  from = "/ruby/instrumentation/namespaces.html"
  to = "/guides/namespaces.html"
[[redirects]]
  from = "/elixir/instrumentation/namespaces.html"
  to = "/guides/namespaces.html"
[[redirects]]
  from = "/nodejs/tracing/namespaces.html"
  to = "/guides/namespaces.html"
[[redirects]]
from = "/ruby/instrumentation/tagging.html"
to = "/guides/custom-data"
[[redirects]]
from = "/elixir/instrumentation/tagging.html"
to = "/guides/custom-data/"
[[redirects]]
from = "/nodejs/tracing/tagging.html"
to = "/guides/custom-data/"
[[redirects]]
from = "/uptime-monitoring.html"
to = "/uptime-monitoring/setup.html"
[[redirects]]
from = "/application/integrations/clubhouse.html"
to = "/application/integrations/shortcut.html"
[[redirects]]
  from = "/nodejs/tracing/"
  to = "/nodejs/instrumentation"

[[redirects]]
from = "/nodejs/tracing/tracer.html"
to = "/nodejs/instrumentation/tracer.html"
[[redirects]]
from = "/nodejs/tracing/span.html"
to = "/nodejs/instrumentation/span.html"

[[redirects]]
from = "/nodejs/tracing/exception-handling.html"
to = "/nodejs/instrumentation/exception-handling.html"

[[redirects]]
from = "/nodejs/tracing/scopes.html"
to = "/nodejs/instrumentation/scopes.html"